.TH "button" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
button \- Pressed button, definned by to frequency\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sinGeneratorEEPROM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfreq_t\fP * \fBfreq_1\fP"
.br
.ti -1c
.RI "\fBfreq_t\fP * \fBfreq_2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pressed button, definned by to frequency\&. 
.PP
Definition at line 60 of file sinGeneratorEEPROM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfreq_t\fP* button::freq_1"

.PP
Definition at line 61 of file sinGeneratorEEPROM\&.h\&.
.SS "\fBfreq_t\fP* button::freq_2"

.PP
Definition at line 62 of file sinGeneratorEEPROM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
