.TH "library/include Directory Reference" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.ti -1c
.RI "file \fBFIFO\&.h\fP"
.br
.RI "Data structure of Buffer, implemented linked list with FIFO specification\&. "
.ti -1c
.RI "file \fBgpio\&.h\fP"
.br
.RI "GPIO library for AVR-GCC\&. "
.ti -1c
.RI "file \fBsinGeneratorEEPROM\&.h\fP"
.br
.ti -1c
.RI "file \fBtimer\&.h\fP"
.br
.RI "Timer library for AVR-GCC\&. "
.ti -1c
.RI "file \fBtwi\&.h\fP"
.br
.ti -1c
.RI "file \fBTWI_LCD\&.h\fP"
.br
.RI "Library for control LCD by using TWI\&. "
.ti -1c
.RI "file \fBTWI_LCD_definitions\&.h\fP"
.br
.RI "Define params of TWI LCD display\&. "
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.in -1c
