.TH "library Directory Reference" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFIFO\&.c\fP"
.br
.ti -1c
.RI "file \fBgpio\&.c\fP"
.br
.ti -1c
.RI "file \fBsinGeneratorEEPROM\&.c\fP"
.br
.RI "Support lib for project\&. Define function for round a flout number into uint8_t, function for generate sin data into EEPROM and structures\&. "
.ti -1c
.RI "file \fBtwi\&.c\fP"
.br
.ti -1c
.RI "file \fBTWI_LCD\&.c\fP"
.br
.ti -1c
.RI "file \fBuart\&.c\fP"
.br
.in -1c
