.TH "library/include/common.h" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/include/common.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDDR\fP(_x)   (*(&_x \- 1))"
.br
.ti -1c
.RI "#define \fBPIN\fP(_x)   (*(&_x \- 2))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common functions and defines\&.
.PP
\fBCopyright\fP
.RS 4
(c) 2019 Tomas Fryza Dept\&. of Radio Electronics, Brno University of Technology, Czechia This work is licensed under the terms of the MIT license\&. 
.RE
.PP

.PP
Definition in file \fBcommon\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define DDR(_x)   (*(&_x \- 1))"
Define address of Data Direction Register of port _x\&. 
.PP
Definition at line 28 of file common\&.h\&.
.SS "#define PIN(_x)   (*(&_x \- 2))"
Define address of input register of port _x\&. 
.PP
Definition at line 33 of file common\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
