.TH "FIFO_note" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FIFO_note
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdata_addres\fP"
.br
.ti -1c
.RI "struct \fBFIFO_note\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file FIFO\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "void* FIFO_note::data_addres"

.PP
Definition at line 18 of file FIFO\&.c\&.
.SS "struct \fBFIFO_note\fP* FIFO_note::next"

.PP
Definition at line 19 of file FIFO\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
