.TH "library/FIFO.c" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/FIFO.c
.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'FIFO\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFIFO_note\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBFIFO_note\fP \fBFIFO_note_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBFIFO_init\fP ()"
.br
.RI "Init Buffer\&. "
.ti -1c
.RI "uint8_t \fBFIFO_add\fP (void *\fBdata\fP)"
.br
.RI "add member into Buffer "
.ti -1c
.RI "void * \fBFIFO_get\fP ()"
.br
.RI "remove one member "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFIFO_note_t\fP * \fBFIFO_first_note\fP"
.br
.ti -1c
.RI "\fBFIFO_note_t\fP * \fBFIFO_last_note\fP"
.br
.ti -1c
.RI "uint16_t \fBFIFO_size\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBFIFO_note\fP \fBFIFO_note_t\fP"

.SH "Function Documentation"
.PP 
.SS "uint8_t FIFO_add (void * data)"

.PP
add member into Buffer 
.PP
\fBParameters\fP
.RS 4
\fI<name>\fP <parameter_description> 
.RE
.PP
\fBReturns\fP
.RS 4
1 if add was successfully otherwise 0 
.RE
.PP

.PP
Definition at line 41 of file FIFO\&.c\&.
.SS "void* FIFO_get ()"

.PP
remove one member 
.PP
\fBReturns\fP
.RS 4
adrress into strucrure  do not forget redefine return value into correct address 
.RE
.PP

.PP
Definition at line 61 of file FIFO\&.c\&.
.SS "void FIFO_init ()"

.PP
Init Buffer\&. <details> 
.PP
Definition at line 34 of file FIFO\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBFIFO_note_t\fP* FIFO_first_note"

.PP
Definition at line 23 of file FIFO\&.c\&.
.SS "\fBFIFO_note_t\fP* FIFO_last_note"

.PP
Definition at line 24 of file FIFO\&.c\&.
.SS "uint16_t FIFO_size"

.PP
Definition at line 25 of file FIFO\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
