.TH "freq" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
freq \- Structure for define frequency and data for generating wave\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sinGeneratorEEPROM\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBc_time\fP"
.br
.ti -1c
.RI "uint8_t \fBc_period\fP"
.br
.ti -1c
.RI "uint8_t \fBc_devider\fP"
.br
.ti -1c
.RI "uint16_t \fBfrequency\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure for define frequency and data for generating wave\&. 
.PP
Definition at line 36 of file sinGeneratorEEPROM\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t freq::c_devider"

.PP
Definition at line 39 of file sinGeneratorEEPROM\&.h\&.
.SS "uint8_t freq::c_period"

.PP
Definition at line 38 of file sinGeneratorEEPROM\&.h\&.
.SS "uint8_t freq::c_time"

.PP
Definition at line 37 of file sinGeneratorEEPROM\&.h\&.
.SS "uint8_t* freq::data_address"

.PP
Definition at line 41 of file sinGeneratorEEPROM\&.h\&.
.SS "uint16_t freq::frequency"

.PP
Definition at line 40 of file sinGeneratorEEPROM\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
