.TH "library/include/timer.h" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
library/include/timer.h \- Timer library for AVR-GCC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <avr/io\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM0_stop\fP()   TCCR0B &= ~((1<<CS02) | (1<<CS01) | (1<<CS00));"
.br
.RI "Defines prescaler CPU frequency values for Timer/Counter0\&. "
.ti -1c
.RI "#define \fBTIM0_overflow_16us\fP()   TCCR0B &= ~((1<<CS02) | (1<<CS01)); TCCR0B |= (1<<CS00);"
.br
.ti -1c
.RI "#define \fBTIM0_overflow_128us\fP()   TCCR0B &= ~((1<<CS02) | (1<<CS00)); TCCR0B |= (1<<CS01);"
.br
.ti -1c
.RI "#define \fBTIM0_overflow_1024us\fP()   TCCR0B &= ~(1<<CS02); TCCR0B |= (1<<CS01) | (1<<CS00);"
.br
.ti -1c
.RI "#define \fBTIM0_overflow_4ms\fP()   TCCR0B &= ~((1<<CS01) | (1<<CS00)); TCCR0B |= (1<<CS02);"
.br
.ti -1c
.RI "#define \fBTIM0_overflow_16ms\fP()   TCCR0B &= ~(1<<CS01); TCCR0B |= (1<<CS02) | (1<<CS00);"
.br
.ti -1c
.RI "#define \fBTIM1_stop\fP()   TCCR1B &= ~((1<<CS12) | (1<<CS11) | (1<<CS10));"
.br
.RI "Defines prescaler CPU frequency values for Timer/Counter1\&. "
.ti -1c
.RI "#define \fBTIM1_overflow_4ms\fP()   TCCR1B &= ~((1<<CS12) | (1<<CS11)); TCCR1B |= (1<<CS10);"
.br
.ti -1c
.RI "#define \fBTIM1_overflow_33ms\fP()   TCCR1B &= ~((1<<CS12) | (1<<CS10)); TCCR1B |= (1<<CS11);"
.br
.ti -1c
.RI "#define \fBTIM1_overflow_262ms\fP()   TCCR1B &= ~(1<<CS12); TCCR1B |= (1<<CS11) | (1<<CS10);"
.br
.ti -1c
.RI "#define \fBTIM1_overflow_1s\fP()   TCCR1B &= ~((1<<CS11) | (1<<CS10)); TCCR1B |= (1<<CS12);"
.br
.ti -1c
.RI "#define \fBTIM1_overflow_4s\fP()   TCCR1B &= ~(1<<CS11); TCCR1B |= (1<<CS12) | (1<<CS10);"
.br
.ti -1c
.RI "#define \fBTIM2_stop\fP()   TCCR2B &= ~((1<<CS22) | (1<<CS21) | (1<<CS20));"
.br
.RI "Defines prescaler CPU frequency values for Timer/Counter2\&. "
.ti -1c
.RI "#define \fBTIM2_overflow_16us\fP()   TCCR2B &= ~((1<<CS22) | (1<<CS21)); TCCR2B |= (1<<CS20);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_124us\fP()   TCCR2B &= ~((1<<CS22) | (1<<CS20)); TCCR2B |= (1<<CS21);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_262us\fP()   TCCR2B &= ~(1<<CS22); TCCR2B |= (1<<CS21) | (1<<CS20);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_1ms\fP()   TCCR2B &= ~((1<<CS21) | (1<<CS20)); TCCR2B |= (1<<CS22);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_2ms\fP()   TCCR2B &= ~(1<<CS21); TCCR2B |= (1<<CS22) | (1<<CS20);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_4ms\fP()   TCCR2B &= ~(1<<CS20); TCCR2B |= (1<<CS22) | (1<<CS21);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_16ms\fP()   TCCR2B |= (1<<CS22) | (1<<CS20) | (1<<CS21);"
.br
.ti -1c
.RI "#define \fBTIM0_overflow_interrupt_enable\fP()   TIMSK0 |= (1<<TOIE0);"
.br
.RI "Defines interrupt enable/disable modes for Timer/Counter0\&. "
.ti -1c
.RI "#define \fBTIM0_overflow_interrupt_disable\fP()   TIMSK0 &= ~(1<<TOIE0);"
.br
.ti -1c
.RI "#define \fBTIM1_overflow_interrupt_enable\fP()   TIMSK1 |= (1<<TOIE1);"
.br
.RI "Defines interrupt enable/disable modes for Timer/Counter1\&. "
.ti -1c
.RI "#define \fBTIM1_overflow_interrupt_disable\fP()   TIMSK1 &= ~(1<<TOIE1);"
.br
.ti -1c
.RI "#define \fBTIM2_overflow_interrupt_enable\fP()   TIMSK2 |= (1<<TOIE2);"
.br
.RI "Defines interrupt enable/disable modes for Timer/Counter2\&. "
.ti -1c
.RI "#define \fBTIM2_overflow_interrupt_disable\fP()   TIMSK2 &= ~(1<<TOIE2);"
.br
.in -1c
.SH "Detailed Description"
.PP 
Timer library for AVR-GCC\&. 

The library contains macros for controlling the timer modules\&.
.PP
\fBNote\fP
.RS 4
Based on Microchip Atmel ATmega328P manual and no source file is needed for the library\&.
.RE
.PP
\fBCopyright\fP
.RS 4
(c) 2019-2020 Tomas Fryza Dept\&. of Radio Electronics, Brno University of Technology, Czechia This work is licensed under the terms of the MIT license\&. 
.RE
.PP

.PP
Definition in file \fBtimer\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM0_overflow_1024us()   TCCR0B &= ~(1<<CS02); TCCR0B |= (1<<CS01) | (1<<CS00);"

.PP
Definition at line 42 of file timer\&.h\&.
.SS "#define TIM0_overflow_128us()   TCCR0B &= ~((1<<CS02) | (1<<CS00)); TCCR0B |= (1<<CS01);"

.PP
Definition at line 41 of file timer\&.h\&.
.SS "#define TIM0_overflow_16ms()   TCCR0B &= ~(1<<CS01); TCCR0B |= (1<<CS02) | (1<<CS00);"

.PP
Definition at line 44 of file timer\&.h\&.
.SS "#define TIM0_overflow_16us()   TCCR0B &= ~((1<<CS02) | (1<<CS01)); TCCR0B |= (1<<CS00);"

.PP
Definition at line 40 of file timer\&.h\&.
.SS "#define TIM0_overflow_4ms()   TCCR0B &= ~((1<<CS01) | (1<<CS00)); TCCR0B |= (1<<CS02);"

.PP
Definition at line 43 of file timer\&.h\&.
.SS "#define TIM0_overflow_interrupt_disable()   TIMSK0 &= ~(1<<TOIE0);"

.PP
Definition at line 77 of file timer\&.h\&.
.SS "#define TIM0_overflow_interrupt_enable()   TIMSK0 |= (1<<TOIE0);"

.PP
Defines interrupt enable/disable modes for Timer/Counter0\&. 
.PP
Definition at line 76 of file timer\&.h\&.
.SS "#define TIM0_stop()   TCCR0B &= ~((1<<CS02) | (1<<CS01) | (1<<CS00));"

.PP
Defines prescaler CPU frequency values for Timer/Counter0\&. 
.PP
\fBNote\fP
.RS 4
F_CPU = 16 MHz 
.RE
.PP

.PP
Definition at line 39 of file timer\&.h\&.
.SS "#define TIM1_overflow_1s()   TCCR1B &= ~((1<<CS11) | (1<<CS10)); TCCR1B |= (1<<CS12);"

.PP
Definition at line 55 of file timer\&.h\&.
.SS "#define TIM1_overflow_262ms()   TCCR1B &= ~(1<<CS12); TCCR1B |= (1<<CS11) | (1<<CS10);"

.PP
Definition at line 54 of file timer\&.h\&.
.SS "#define TIM1_overflow_33ms()   TCCR1B &= ~((1<<CS12) | (1<<CS10)); TCCR1B |= (1<<CS11);"

.PP
Definition at line 53 of file timer\&.h\&.
.SS "#define TIM1_overflow_4ms()   TCCR1B &= ~((1<<CS12) | (1<<CS11)); TCCR1B |= (1<<CS10);"

.PP
Definition at line 52 of file timer\&.h\&.
.SS "#define TIM1_overflow_4s()   TCCR1B &= ~(1<<CS11); TCCR1B |= (1<<CS12) | (1<<CS10);"

.PP
Definition at line 56 of file timer\&.h\&.
.SS "#define TIM1_overflow_interrupt_disable()   TIMSK1 &= ~(1<<TOIE1);"

.PP
Definition at line 83 of file timer\&.h\&.
.SS "#define TIM1_overflow_interrupt_enable()   TIMSK1 |= (1<<TOIE1);"

.PP
Defines interrupt enable/disable modes for Timer/Counter1\&. 
.PP
Definition at line 82 of file timer\&.h\&.
.SS "#define TIM1_stop()   TCCR1B &= ~((1<<CS12) | (1<<CS11) | (1<<CS10));"

.PP
Defines prescaler CPU frequency values for Timer/Counter1\&. 
.PP
\fBNote\fP
.RS 4
F_CPU = 16 MHz 
.RE
.PP

.PP
Definition at line 51 of file timer\&.h\&.
.SS "#define TIM2_overflow_124us()   TCCR2B &= ~((1<<CS22) | (1<<CS20)); TCCR2B |= (1<<CS21);"

.PP
Definition at line 66 of file timer\&.h\&.
.SS "#define TIM2_overflow_16ms()   TCCR2B |= (1<<CS22) | (1<<CS20) | (1<<CS21);"

.PP
Definition at line 71 of file timer\&.h\&.
.SS "#define TIM2_overflow_16us()   TCCR2B &= ~((1<<CS22) | (1<<CS21)); TCCR2B |= (1<<CS20);"

.PP
Definition at line 65 of file timer\&.h\&.
.SS "#define TIM2_overflow_1ms()   TCCR2B &= ~((1<<CS21) | (1<<CS20)); TCCR2B |= (1<<CS22);"

.PP
Definition at line 68 of file timer\&.h\&.
.SS "#define TIM2_overflow_262us()   TCCR2B &= ~(1<<CS22); TCCR2B |= (1<<CS21) | (1<<CS20);"

.PP
Definition at line 67 of file timer\&.h\&.
.SS "#define TIM2_overflow_2ms()   TCCR2B &= ~(1<<CS21); TCCR2B |= (1<<CS22) | (1<<CS20);"

.PP
Definition at line 69 of file timer\&.h\&.
.SS "#define TIM2_overflow_4ms()   TCCR2B &= ~(1<<CS20); TCCR2B |= (1<<CS22) | (1<<CS21);"

.PP
Definition at line 70 of file timer\&.h\&.
.SS "#define TIM2_overflow_interrupt_disable()   TIMSK2 &= ~(1<<TOIE2);"

.PP
Definition at line 89 of file timer\&.h\&.
.SS "#define TIM2_overflow_interrupt_enable()   TIMSK2 |= (1<<TOIE2);"

.PP
Defines interrupt enable/disable modes for Timer/Counter2\&. 
.PP
Definition at line 88 of file timer\&.h\&.
.SS "#define TIM2_stop()   TCCR2B &= ~((1<<CS22) | (1<<CS21) | (1<<CS20));"

.PP
Defines prescaler CPU frequency values for Timer/Counter2\&. 
.PP
\fBNote\fP
.RS 4
F_CPU = 16 MHz 
.RE
.PP

.PP
Definition at line 64 of file timer\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
