.TH "xvymaz" 3 "Tue Dec 15 2020" "Version v1.0" "Waveform generator with R-2R DAC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xvymaz \- waveform generator <main\&.c>
.PP
 \- Project witch demotrate generatiting of DTFM, sine, square, triabgle and sawtooth signal from 200 to 2 KHz\&.Some kinds of signals supports seting of amplitude from 0 to 5 V devided into 255 steps\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Project witch demotrate generatiting of DTFM, sine, square, triabgle and sawtooth signal from 200 to 2 KHz\&.Some kinds of signals supports seting of amplitude from 0 to 5 V devided into 255 steps\&. 


.PP
.nf
#include "FIFO\&.h" #include "TWI_LCD\&.h" #include "sinGeneratorEEPROM\&.h" 

.fi
.PP
.PP
\fBAuthor\fP
.RS 4
Tomas Vymazal xvymaz11@vutbr.cz https://github.com/vymaztom
.RE
.PP
\fBVersion\fP
.RS 4
v1\&.0
.RE
.PP
\fBCopyright\fP
.RS 4
(C) 2020 Tomas Vymazal, MIT License 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Waveform generator with R-2R DAC from the source code\&.
